config/routes.rb
Rails.application.routes.draw do
  root 'paths#edit'
  patch 'update' => 'paths#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/path.rb
class Path < ApplicationRecord
end

app/models/scheduler.rb
# app/models/scheduler.rb
class Scheduler
  def self.run_daily_tasks
    article = WebScraper.get_qiita_post_titles_links
    PathsController.slack_bot(article)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  def edit
    @path = Path.last
  end

  def update
    # pathは常に1件
    @path = Path.find(1)
    if @path.update(path_params)
      redirect_to root_path, notice: '設定が完了しました。明日の8時から適用されます。'
    else
      render :edit
    end
  end

  private

  def path_params
    params.require(:path).permit(:path)
  end
  def self.slack_bot(articles)
    notifier = Slack::Notifier.new ENV['WEBHOOK_URL'] do
      defaults channel: "#目指せ宮嶋", username: "通知BOT"
    end

    tag = Path.first.path.split('/').last
    articles.unshift("<設定タグ: #{tag}>")
    articles.unshift("【おはようございます。本日の新着記事です!】")
    message = articles.join("\n")
    notifier.ping message  # Slackに通知するメッセージ
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>目指せ宮嶋！</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p&display=swap" rel="stylesheet"> 
  </head>

  <body>
    <% if flash.notice %>
      <p class="notice"><%= flash.notice %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/paths/edit.html.erb
<div class="container">
  <h1>目指せ宮嶋！</h1>

  <p>このアプリはキータの最新記事５件を取得するアプリです。</p>

  <div class="image-container">
    <%= image_tag("profile.png", alt: "miyajima-sensei", class: "center-image") %>

    <div class="form-container">
      <%= form_with(model: @path, url: update_path, local: true, method: :patch) do |form| %>
        <div class="field">
          <%# <%= form.label :path, "タグ名" %>
          <%# <%= form.text_field :path, id: :path_path %>
          <% options = [
            ["タグを選択して下さい", "https://qiita.com/"],
            ["ruby", "https://qiita.com/tags/ruby"],
            ["python", "https://qiita.com/tags/python"],
            ["javascript", "https://qiita.com/tags/javascript"]
            ]
          %>
          <%= form.select :path, options, {}, class: "form_select" %>
        </div>

        <div class="actions">

          <%= form.submit "タグを設定します", class: "submit_button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>